# SPDX-FileCopyrightText: 2022 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

nameOverride: ""
fullnameOverride: ""

replicaCount: 1
annotations: {}

image:
  repository: logm250/gnmi-simulator
  tag: 0.6.9
  pullPolicy: IfNotPresent
  pullSecrets: []

resources:
  requests:
    cpu: 0.5
    memory: 512Mi

service:
  type: ClusterIP

ports:
  gnmi:
    secure: 10161
    insecure: 11161

nodeSelector: {}

tolerations: []

affinity: {}
