# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: raft.atomix.io/v1beta3
kind: DataStore
metadata:
  name: {{ template "device-provisioner.atomix.consensus.store.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ template "device-provisioner.atomix.consensus.store.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  cluster:
    name: {{ template "device-provisioner.atomix.consensus.cluster.name" . }}
  partitions: {{ .Values.atomix.store.consensus.partitions }}
  {{- with .Values.atomix.store.consensus.config.electionRTT }}
  electionRTT: {{ . }}
  {{- end }}
  {{- with .Values.atomix.store.consensus.config.heartbeatRTT }}
  heartbeatRTT: {{ . }}
  {{- end }}
  {{- with .Values.atomix.store.consensus.config.snapshotEntries }}
  snapshotEntries: {{ . }}
  {{- end }}
  {{- with .Values.atomix.store.consensus.config.compactionOverhead }}
  compactionOverhead: {{ . }}
  {{- end }}
  {{- with .Values.atomix.store.consensus.config.maxInMemLogSize }}
  maxInMemLogSize: {{ . }}
  {{- end }}
---
# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

# Create a DataStore with the configuration for the store
apiVersion: atomix.io/v3beta4
kind: DataStore
metadata:
  name: {{ template "device-provisioner.atomix.consensus.store.name" . }}
  labels:
    name: {{ template "device-provisioner.atomix.consensus.store.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  # Configure the DataStore to use the etcd driver with the v3 API
  driver:
    name: atomix.io/etcd
    apiVersion: v3
  # Define the configuration to be passed to the driver to connect to the store
  config:
    endpoints:
      - clustermesh-apiserver:2379