# SPDX-FileCopyrightText: 2022-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ template "device-provisioner.fullname" . }}
  namespace: {{ .Release.Namespace }}-data
rules:
- apiGroups:
  - primitives.atomix.io
  resources:
  - '*'
  resourceNames:
  - {{ template "device-provisioner.fullname" . }}-objects
  verbs:
  - '*'