# SPDX-FileCopyrightText: 2022-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: onos-ubrella-device-provisioner
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - primitives.atomix.io
  resources:
  - '*'
  resourceNames:
  - onos-ubrella-device-provisioner-objects
  verbs:
  - '*'