# SPDX-FileCopyrightText: 2022 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: onos-config
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - primitives.atomix.io
  resources:
  - '*'
  resourceNames:
  - onos-config-leaderships
  - onos-config-masterships
  - onos-config-network-changes
  - onos-config-device-changes
  - onos-config-snapshots
  - onos-config-network-snapshots
  - onos-config-device-snapshots
  - onos-config-transactions
  - onos-config-proposals
  - onos-config-configurations

  verbs:
  - '*'