# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: onos-raft
description: Umbrella chart to deploy all µONOS
kubeVersion: ">=1.17.0"
type: application
version: 1.3.32
appVersion: v1.1.0
keywords:
  - onos
  - sdn
home: https://onosproject.org
maintainers:
  - name: ONOS Support
    email: support@opennetworking.org

